apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/ip-allocated-from-pool: default
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  externalTrafficPolicy: Local
  externalIPs:
  - 10.100.8.119
  - 10.100.8.120
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
